package com.stanfy.android.gradle.apt;

import com.android.build.gradle.AppExtension;
import com.android.build.gradle.BaseExtension;
import com.android.build.gradle.LibraryExtension;
import com.android.build.gradle.api.BaseVariant;
import org.gradle.api.Action;
import org.gradle.api.DomainObjectSet;
import org.gradle.api.GradleException;
import org.gradle.api.Plugin;
import org.gradle.api.Project;
import org.gradle.api.Task;
import org.gradle.api.tasks.compile.JavaCompile;

import java.io.File;
import java.util.Arrays;

/**
 * Makes sources generated by annotation processors visible in Android Studio.
 */
public class AndroidAptPlugin implements Plugin<Project> {

  @Override
  public void apply(final Project project) {
    BaseExtension ext = (BaseExtension) project.getExtensions().findByName("android");
    if (ext == null) {
      throw new GradleException("Not Androif project");
    }

    final DomainObjectSet<? extends BaseVariant> variants;
    if (ext instanceof AppExtension) {
      variants = ((AppExtension) ext).getApplicationVariants();
    } else {
      variants = ((LibraryExtension) ext).getLibraryVariants();
    }

    final File aptOutputDir = project.file(new File(project.getBuildDir(), "generated/source/apt"));

    variants.all(new Action<BaseVariant>() {
      @Override
      public void execute(final BaseVariant v) {
        final File aptOutput = new File(aptOutputDir, v.getDirName());
        v.addJavaSourceFoldersToModel(aptOutput);
        JavaCompile javaCompile = v.getJavaCompile();
        javaCompile.getOptions().getCompilerArgs().addAll(Arrays.asList("-s", aptOutput.getAbsolutePath()));
        javaCompile.doFirst(new Action<Task>() {
          @Override
          public void execute(final Task task) {
            aptOutput.mkdirs();
          }
        });
      }
    });
  }

}
